name: Release Plugin
on: push

jobs:
    create-archive:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Sources
              uses: actions/checkout@v4

            - name: Create License Artifact
              if: startsWith(github.ref, 'refs/tags/')
              uses: actions/upload-artifact@v4
              with:
                name: licensing-info
                path: LICENSE

            - name: Create Directory Structure and Archive
              shell: bash
              run: |
                rm LICENSE
                rm README.md
                mkdir ggl-post-types
                shopt -s extglob
                mv !(ggl-post-types|.git|.github) ggl-post-types/
                mv ggl-post-types/loader.php ggl-post-type.loader.php
                zip -r custom-post-types.zip ggl-post-type.loader.php ggl-post-types/*
            
            - name: Create Release Artifact
              if: startsWith(github.ref, 'refs/tags/')
              uses: actions/upload-artifact@v4
              with:
                name: release-artifacts
                path: custom-post-types.zip
                retention-days: 1
                
            - name: Create Artifact
              if: startsWith(github.ref, 'refs/heads/')
              uses: actions/upload-artifact@v4
              with:
                name: debug-artifacts
                path: custom-post-types.zip
                retention-days: 7
    
    release-archive:

        permissions:
            contents: write

        if: startsWith(github.ref, 'refs/tags/')
        needs:
            - create-archive
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                merge-multiple: true

            - name: Add Tag to Archive
              run: |
                mv custom-post-types.zip  custom-post-types.${{ github.ref_name }}.zip
            
            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                generate_release_notes: true
                draft: true
                files: |
                  custom-post-types.${{ github.ref_name }}.zip
                  LICENSE
